SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `cgt456` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `cgt456`;

CREATE TABLE IF NOT EXISTS `main` (
  `fbID` bigint(25) NOT NULL,
  `gdID` text NOT NULL,
  `dbID` text NOT NULL,
  PRIMARY KEY (`fbID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `main` (`fbID`, `gdID`, `dbID`) VALUES
(10203794539368727, '{"access_token":"ya29.1.AADtN_U0TX0CprLaigOioOCVwphmi6ci1DhVFL6HNaRrsDtIbOkG0dKxlcmp51s","token_type":"Bearer","expires_in":3600,"refresh_token":"1/Ea8gXU6u0aVlUEUo2Y38tHRss3hNQnrdY5-U0Ss_3H0","created":1399011156}', 'sPwYOQp-KhwAAAAAAAAEABm6xcz5ZLC2WgC3IAJjiM184ESkLYmEONwgup_IwXtt');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
